#!/usr/bin/env bash
# installs and configures a nginx server
apt-get install nginx -y;
service nginx start;
chmod 666 /usr/share/nginx/html/index.html;
echo -e 'Hello World!' > /usr/share/nginx/html/index.html;
service nginx reloa
d
