#!/usr/bin/env bash
# a script that installs nginx and configures index.html
sudo apt-get install -y nginx &&
    sudo mkdir -p /var/www/html/ &&
    echo "Hello World!" | tee /var/www/html/index.html &&
    service nginx start
