#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/; }' /etc/nginx/sites-available/default
sudo service nginx restart

